workflows:
    android-workflow-id:
        name: Android Sample Workflow
        # .......    
        # .......
        # .......  
    ios-native:
      name: IOS Workflow
      max_build_duration: 120
      instance_type: mac_mini_m1
      environment:
        vars:
          BUNDLE_ID: "com.harveydensem.drp"
          XCODE_PROJECT: "drp.xcodeproj" # <-- Name of your Xcode project
          XCODE_SCHEME: "drp" # <-- Name of your Xcode scheme
        xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
        cocoapods: default
      scripts:
        # - name: Install CocoaPods dependencies
        #   script: | 
        #     cd drp/ios
        #     pod install
        
        #- name: Set up code signing settings on Xcode project
         # script: xcode-project use-profiles
          
        - name: Build ipa for distribution
          script: |
            xcode-project build-ipa \
              --project "$CM_BUILD_DIR/drp/ios/$XCODE_PROJECT" \
              --scheme "$XCODE_SCHEME"
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO
      artifacts:
        - build/ios/ipa/*.ipa
        - /tmp/xcodebuild_logs/*.log
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
