defaults:
  run:
    shell: bash

  #on:
  # deployment:
  # types: [created]

on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./drp-frontend/drp/drp-2024

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Specify the Java version you want to use here
        distribution: 'adopt'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'

    - name: Install dependencies
      run: |
        npm install
        npm install -g eas-cli
    - name: Initialise eas
      run: eas init
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Build for Android
      run: eas build --platform android --non-interactive --local
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Convert to apk
      run: |
        java -jar ./scripts/bundletool-all-1.16.0.jar build-apks --bundle="$(ls *.aab | head -n 1)" --output="out.apks" --mode=universal 
        mv out.apks out.zip
        unzip out.zip
        java -jar ./scripts/uber-apk-signer-1.3.0.jar --apks universal.apk

    - name: Move apk build to latest release folder
      run: rm -f ../../../latest-release/android/* | mv universal-aligned-debugSigned.apk ../../../latest-release/android/

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: ./latest-release/android/universal-aligned-debugSigned.apk

  deploy:
    runs-on: ubuntu-latest
    needs: build-android

    defaults:
      run:
        working-directory: ./drp-frontend/drp/drp-2024

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Download APK Artifact
      uses: actions/download-artifact@v2
      with:
        name: android-apk
        path: ./latest-release/android

    - name: Commit APK to repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b latest-release
        git add ../../../latest-release/android/universal-aligned-debugSigned.apk
        git add -u
        git commit -m "BOT: Added built APK"
        git push -f origin latest-release
