defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main

jobs:
  build-ios:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./drp-frontend

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Specify the Java version you want to use here
        distribution: 'adopt'

    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@ec02537da5712d66d4d50a0f33b7eb52773b5ed1
      with:
        ruby-version: '3.1' # Not needed with a .ruby-version file
    - run: bundle install
    - run: bundle exec rake

    - name: Set up fastlane
    - run: gem install fastlane -NV
    
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'

    - name: Install dependencies
      run: |
        npm install
        npm install -g eas-cli
        npx expo install expo-dev-client
        
    - name: Initialise eas
      run: eas init
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Build for IOS
      run: eas build --platform ios --local --non-interactive --profile preview
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Move ipa build to latest release folder
      run: rm -f ../latest-release/* | mv *.ipa ../latest-release/

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ios-ipa
        path: ./latest-release/*.ipa

    
  deploy:
    runs-on: ubuntu-latest
    needs: build-ios

    defaults:
      run:
        working-directory: ./drp-frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Download IPA Artifact
      uses: actions/download-artifact@v2
      with:
        name: ios-ipa
        path: ./latest-release

    - name: Commit IPA to repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b latest-release
        git add ../latest-release/*
        git commit -m "BOT: Added built IPA"
        git push origin latest-release
