defaults:
  run:
    shell: bash

<<<<<<< Updated upstream
on:
  deployment:
    types: [created]
=======
      #on:
      # push:
      # branches:
      #  - main
>>>>>>> Stashed changes

jobs:
  build-ios:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: ./drp-frontend/drp/drp-2024

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Specify the Java version you want to use here
        distribution: 'adopt'

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'

    - name: Install dependencies
      run: |
        npm install
        npm install -g eas-cli
        npx expo install expo-dev-client
        
    - name: Initialise eas
      run: eas init
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Build for IOS
      run: |
        npx expo prebuild
        cd ios 
        pod install
        echo before
        ls
        echo after
        xcodebuild -project drp2024.xcodeproj -scheme drp2024 -sdk iphoneos -configuration Debug --archive-xcargs "CODE_SIGN_STYLE=Manual"
        xcodebuild archive -project drp2024.xcodeproj -scheme drp2024 -sdk iphoneos -configuration Release -archivePath drp2024.xcarchive
        xcodebuild -exportArchive -archivePath drp2024.xcarchive -exportPath ./ExportedIPA -exportOptionsPlist ../exportOptions.plist
        ls

      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Unzip IOS build
      run: tar -czf *.tar.gz ios-build.ipa

    - name: Move ipa build to latest release folder
      run: rm -f ../../../latest-release/ios/* | mv *.ipa ../../../latest-release/ios/

    - name: Upload IPA Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ios-ipa
        path: ./latest-release/ios/*.ipa

    
  deploy:
    runs-on: ubuntu-latest
    needs: build-ios

    defaults:
      run:
        working-directory: ./drp-frontend/drp/drp-2024

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Download IPA Artifact
      uses: actions/download-artifact@v2
      with:
        name: ios-ipa
        path: ./latest-release/ios

    - name: Commit IPA to repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config pull.rebase false
        git checkout -b latest-release
        git pull origin latest-release
        git add ../../../latest-release/ios/*
        git add -u
        git commit -m "BOT: Added built IPA"
        git push origin latest-release

