defaults:
  run:
    shell: bash
    
on:
  push:
    branches:
      - main

jobs:
  build-android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./drp-frontend   

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17' # Specify the Java version you want to use here
        distribution: 'adopt'
        
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'

    - name: Install dependencies
      run: |
        npm install
        npm install -g eas-cli
    - name: Initialise eas
      run: eas init
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
    - name: Build for Android
      run: eas build --platform android --non-interactive --local
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Move apk build to latest release folder
    - run: rm -f ./latest-release/* | mv *.aab ./latest-release/

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v2
      with:
        name: android-apk
        path: ./drp-frontend/latest-release/*.aab
      
      
    # - name: Build for iOS
    #   run: eas build --platform ios --non-interactive
    #   env:
    #     EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
        
  deploy:
    runs-on: ubuntu-latest
    needs: build-android

    defaults:
      run:
        working-directory: ./drp-frontend

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Download APK Artifact
      uses: actions/download-artifact@v2
      with:
        name: android-apk
        path: ./drp-frontend/latest-release

    - name: Commit APK to repository
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add ./latest-release/*
        git commit -m "BOT: Added built APK"
        git push
