defaults:
  run:
    shell: bash
    
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./drp

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.10.0'

    - name: Install dependencies
      run: |
        npm install
        npm install -g eas-cli

    - name: Authenticate with EAS
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      run: eas login --auth-token $EXPO_TOKEN

    - name: Build for Android
      run: eas build --platform android --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    # - name: Build for iOS
    #   run: eas build --platform ios --non-interactive
    #   env:
    #     EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
